name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install pipenv
      run: |
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv install --dev
    
    - name: Run linting
      run: |
        pipenv run lint
    
    - name: Run unit tests
      run: |
        pipenv run test-unit
    
    - name: Run unit tests with coverage
      run: |
        pipenv run test-cov tests/unit/

  integration-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    
    strategy:
      matrix:
        python-version: [3.11]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install pipenv
      run: |
        pip install pipenv
    
    - name: Install dependencies
      run: |
        pipenv install --dev
    
    - name: Run integration tests
      run: |
        pipenv run test-integration
    
    - name: Run all tests with coverage
      run: |
        pipenv run test-cov
